-- Creating the 'items' table
CREATE TABLE IF NOT EXISTS public.items
(
    item_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    item_name character varying(255) COLLATE pg_catalog."default",
    category character varying(255) COLLATE pg_catalog."default",
    image character varying(255) COLLATE pg_catalog."default",
    price double precision NOT NULL,
    is_delete boolean NOT NULL,
    CONSTRAINT items_pkey PRIMARY KEY (item_id)
);

-- Creating the 'orders' table
CREATE TABLE IF NOT EXISTS public.orders
(
    order_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    order_date timestamp(6) without time zone,
    phone character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    comment character varying(255) COLLATE pg_catalog."default",
    order_type character varying(255) COLLATE pg_catalog."default",

    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

-- Creating the 'order_items' table
CREATE TABLE IF NOT EXISTS public.order_items
(
    order_item_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    quantity integer NOT NULL,
    item_item_id bigint,
    order_order_id bigint,
    CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id),
    CONSTRAINT fk_order FOREIGN KEY (order_order_id)
        REFERENCES public.orders (order_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_item FOREIGN KEY (item_item_id)
        REFERENCES public.items (item_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- Creating the 'users' table
CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    username character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default",
    is_active boolean NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);
